version: "3.7"
services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - coolify    
    expose:
      - "8080"   
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_HOSTNAME}
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}     
      - REDIS_USER=${REDIS_USER}  

      # Generate this with: openssl rand -hex 32
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY}
      - SEARXNG_LIMITER=true
      - SEARXNG_IMAGE_PROXY=true
      - SEARXNG_CORS_ALLOWED_ORIGINS=${SEARXNG_ALLOWED_ORIGINS_ARRAY}
      # or for all origins (less secure):
      # - SEARXNG_CORS_ALLOWED_ORIGINS=["*"]
      - SEARXNG_HTTP_HEADERS_ACCESS_CONTROL_ALLOW_ORIGIN=${SEARXNG_ALLOWED_ORIGINS}
      # or for all origins (less secure):
      # - SEARXNG_HTTP_HEADERS_ACCESS_CONTROL_ALLOW_ORIGIN="*"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  coolify:
    external: true    
