version: "3.7"
services:
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - coolify    
    expose:
      - "8080"   
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      # Basic Configuration
      - SEARXNG_BASE_URL=${SEARXNG_HOSTNAME}
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS}

      # Redis Configuration (using your existing coolify-redis)
      - SEARXNG_REDIS_URL=${SEARXNG_REDIS_URL}

      # Generate this with: openssl rand -hex 32
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY}
      - SEARXNG_IMAGE_PROXY=true

      # Bot Protection
      - SEARXNG_LIMITER=true
      - SEARXNG_BOT_PROTECTION=true

       # CORS settings
      - SEARXNG_CORS_ALLOWED_ORIGINS=${SEARXNG_ALLOWED_ORIGINS_ARRAY}
      - SEARXNG_HTTP_HEADERS_ACCESS_CONTROL_ALLOW_ORIGIN=${SEARXNG_ALLOWED_ORIGINS}

      # User Agent
      - SEARXNG_HTTP_HEADERS_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
       
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  coolify:
    external: true    
